name:                replique
synopsis:            Replique is a high-level REPL library for building command line interfaces.
version:             0.1.0.0
github:              "lpeterse/haskell-replique"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/haskell-replique#readme>

dependencies:
- base >= 4.7 && < 5
- async
- bytestring
- exceptions
- stm
- text
- transformers
- prettyprinter
- terminal
- megaparsec

library:
  ghc-options: -Werror -O2 -fwarn-incomplete-patterns
  exposed-modules:
    - Control.Monad.Replique
    - Control.Monad.Replique.IO
  other-modules:
    - Control.Monad.Replique.RepliqueT
  source-dirs: src

executables:
  replique-demo:
    main:                Main.hs
    source-dirs:         app/replique-demo
    ghc-options:
    - -O2
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - terminal
    - replique
