name:                replique
synopsis:            Replique is a high-level REPL library for building command line interfaces
version:             0.1.0.0
github:              "lpeterse/haskell-replique"
license:             BSD3
author:              "Lars Petersen"
maintainer:          "info@lars-petersen.net"
copyright:           "2018 Lars Petersen"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on Github at <https://github.com/lpeterse/haskell-replique#readme>

dependencies:
- base >= 4.7 && < 5
- async
- exceptions
- mtl
- prettyprinter
- stm
- terminal
- text
- transformers

default-extensions:
- LambdaCase
- MultiWayIf
- BlockArguments
- OverloadedStrings
- GeneralizedNewtypeDeriving
- TypeFamilies
- FlexibleContexts
- FlexibleInstances

library:
  ghc-options: -Wall -fwarn-incomplete-patterns
  exposed-modules:
    - System.Terminal.Replique
    - System.Terminal.Replique.Monad
    - System.Terminal.Replique.Readable
    - System.Terminal.Replique.Readline
    - System.Terminal.Replique.RepliqueT
    - System.Terminal.Replique.TextEdit
  source-dirs: src

executables:
  replique-demo:
    main:                Main.hs
    source-dirs:         app/replique-demo
    ghc-options:
    - -O2
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - terminal
    - replique

tests:
  replique-tests:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminal
    - replique
    - tasty
    - tasty-hunit
    - tasty-quickcheck
